notifications:
  email: false
language: node_js
node_js:
- node
deploy:
  provider: npm
  email:
    secure: vbiHRzn6YU5FMKwhFjxuRhLkvwpH/9xsL959EhLMwl1Td/pUWY7ZsS9MXsDKNhuRScU7inwcUBGh6Re/P10k7MvOmOcSxZkPXyHlmF+zj07vslOkqmADrqiemXse5fyTmUikG8pg2OnJ/a3esGb/2Re/n8rb2+eY49tMeNhdWnGTaKAAxIEB14R+zUf6fh2x+/b2+t1w9lYcqrqoPnb32mgvruGcssKAkSWOEI64e/5kjRT50UtnbDF1CAFcecFonJQ+Lm2bOlsjW8Vre33RgrARacbusQKdoWeVbZWlcbhwm7EHYO5JBHpx/Nog73bvSyCH7dPQarvEDShwao6OjpGnvx8sFvg2bYDkTy43l5UEP4Wlvvt2KtyFoe/JZA9S+jXMAnr//00LxmitH7wZ+jUeO1QZd/PkDckYM27Nwkab56irPS4UsFDkDFr42NQHs6QI94OIwZG9IWbOzheb0zDnVVq0A4oBedUCX/Ukpd4K2J0D/7CJrjtmUHbB1m/k4omRmDj9MW8TzB2wCO7IPkMXAEatNSkyPDzgpIf+dbyrqmVX4mAwZN1Wt9/7JrYhACA7oPLy863RjYhporl3jGQ9S8h9tgLuenDdupvNo84hazwA0+I4JpQXXNam4kQC9krOrt6Ki+9no8yE2lhzMHnt2hL78ix4Sx4OlaNLO2g=
  api_key:
    secure: u+rg/Z8InWGcQCwu4VG0FjUJMPbXmWIvrTSQaEqoOa6U68sXN6CVQjOKcnDenX6ZZ9do4SoC6DS9/eWbvOiP35q2gqpxVvivIW0ABt20iRMZyAl9D1qzzlNVGmF9ctnNpGgD4DwhCJzJJH54dcv/2Y3Eum8tz0MTmr9K0eUTNWAXb2F6lYzf9NskGxHgwOvd7umtlo3YIFLtJmF52YCCsQuwjRauO9lsMNQQ1XGfbJs0c/g4Wp/K6Qg68Kco3WnWcpZ0RiFABCOyHKbrDww6WF3wmr14aOMh45ZFhjooXanBqK6QYAtJ6RAWL75HJNg/7Aq2q00S0ndmAqsyMS5KaIoVZO607AcUWXmRErcSMLu7QdObzKA60DeoRESU/yCh+tcmRWzurZTUdDAucBAeFtxnQfwNmpO3wO2Dm9heq7wVXlk6cedK7IjyNvpexF4H6El88LUX1CJhuo3oKcOx/JfibWIrdX77qNPo2JqIge458E3b+yfOJqi93O1FvgQVh7koDXRnizgd4z5F0eaVYKXnPJ1UKWCbIus4ki6pyWPpOLJdnquG/o8+WI+iLUnlAC6Y0RU16GTe0ei8leC0uQaAN7qXAbxPDPGHhrpjXCkfMAoBzBIPxWQTuT/vWJJBas16j0gBocAvs8aJr6krMyAQkSBxZrMJ2p/XGmRQKNo=
  on:
    tags: true
